#!/usr/bin/python3
def dict_name (keys, values, fill_value=None):
    if not isinstance(keys, list) or not isinstance(values, list):
        raise TypeError("2 elments, 'Keys' and 'values' must be arr")

    if len(keys) > len(values):
        values.extend([fill_value] * (len(keys) -len(values)))
    elif len(values) > len(keys):
        values = values[:len(keys)]
    return dict(zip(keys, values))

keys = ["name", "age", "city", "Email"]
values = ["Alice", 25, "New York"]

custom_dict = dict_name(keys, values, fill_value="not given")
print(custom_dict)
